# GitHub Actions Workflow para proyectos Angular
name: Angular CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x] # Incluye versiones compatibles con Angular
        # Nota: Angular CLI aún no es totalmente compatible con Node.js 22.x

    steps:
      # Paso 1: Checkout del código fuente
      - name: Checkout source code
        uses: actions/checkout@v4

      # Paso 2: Configurar la versión de Node.js
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Paso 3: Instalar dependencias
      - name: Install dependencies
        run: npm ci

      # Paso 4: Ejecutar pruebas (opcional)
      - name: Run tests
        run: npm test

      # Paso 5: Construir la aplicación Angular
      - name: Build Angular app
        run: npm run build -- --configuration=production

      # Paso 6: Guardar los artefactos del build (opcional)
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: angular-dist
          path: dist/
      # Paso 7: Despliegue a GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/porfolio-n
